# PlatformIO — LILYGO T-Dongle-S3 (ESP32-S3)

[platformio]
default_envs = T-Dongle-S3

[env:T-Dongle-S3]
platform = espressif32@6.12.0
framework = arduino
board = dongles3

board_build.partitions = partitions.csv

upload_speed = 921600
monitor_speed = 115200

; Enable USB CDC for serial console
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
